src/SimpleBlog.Web/ViewModels/ConfigViewModel.cs
using System;

namespace SimpleBlog.ViewModels
{
    public class ConfigViewModel
    {
        public string SiteTitle { get; set; }

        public string ThemeName { get; set; }
    }
}

src/SimpleBlog.Web/ViewModels/PostViewModel.cs
using System;

namespace SimpleBlog.ViewModels
{
    public class PostViewModel
    {
        public string Title { get; set; }

        public string Body { get; set; }

        public string BodyHtml
        {
            get
            {
                return CommonMark.CommonMarkConverter.Convert(Body);
            }
        }

        public DateTime TimeStamp { get; set; }

        public string Author { get; set; }

        public string Slug { get; set; }
    }
}

src/SimpleBlog.Web/Components/SiteTitleViewComponent.cs
using Microsoft.AspNet.Mvc;
using SimpleBlog.Shared;
using System;
using System.Threading.Tasks;

namespace SimpleBlog.Components
{
    public class SiteTitleViewComponent : ViewComponent
    {
        private readonly IConfigService configService;

        public SiteTitleViewComponent(IConfigService configService)
        {
            this.configService = configService;
        }

        public async Task<string> InvokeAsync()
        {
            var config = await configService.LoadConfig();
            return config.SiteTitle;
        }
    }
}

src/SimpleBlog.Web/Components/ThemeContentFolderViewComponent.cs
using Microsoft.AspNet.Mvc;
using SimpleBlog.Shared;
using System;
using System.Threading.Tasks;

namespace SimpleBlog.Components
{
    public class ThemeContentFolderViewComponent : ViewComponent
    {
        private readonly IConfigService configService;

        public ThemeContentFolderViewComponent(IConfigService configService)
        {
            this.configService = configService;
        }

        public async Task<string> InvokeAsync()
        {
            var config = await configService.LoadConfigAsync();
            var themeName = config.ThemeName ?? string.Empty;
            return "/themes/" + themeName;
        }
    }
}

src/SimpleBlog.Web/Components/ThemeNameViewComponent.cs
using Microsoft.AspNet.Mvc;
using SimpleBlog.Shared;
using System;
using System.Threading.Tasks;

namespace SimpleBlog.Components
{
    public class ThemeNameViewComponent : ViewComponent
    {
        private readonly IConfigService configService;

        public ThemeNameViewComponent(IConfigService configService)
        {
            this.configService = configService;
        }

        public async Task<string> InvokeAsync()
        {
            var config = await configService.LoadConfigAsync();
            return config.ThemeName ?? string.Empty;
        }
    }
}

src/SimpleBlog.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using SimpleBlog.Shared;
using System.Threading.Tasks;

namespace SimpleBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostService postService;

        private readonly IConfigService configService;

        public HomeController(IPostService postService, IConfigService configService)
        {
            this.postService = postService;
            this.configService = configService;
        }

        public async Task<IActionResult> Index()
        {
            return await GetViewForObject(postService.Posts.OrderByDescending(p => p.TimeStamp));
        }

        public async Task<IActionResult> GetViewForObject(object model)
        {
            var config = await configService.LoadConfigAsync();

            var themeName = config.ThemeName;

            if (String.IsNullOrWhiteSpace(themeName))
            {
                // return default unthemed view
                return View(model);
            }
            else
            {
                // return the correct view taking theme into account
                return View(string.Format("~/Views/Themes/{0}/{1}/{2}", themeName, RouteData.Values["Controller"], RouteData.Values["Action"]), model);
            }
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

src/SimpleBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{
        var title = await Component.InvokeAsync("SiteTitle");
    }
    <title>@ViewBag.Title - @title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container body-content">
        <h1>@title</h1>
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @title</p>
        </footer>
    </div>
    <script src="~/lib/jquery/js/jquery.js"></script> 
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/SimpleBlog.Web/Views/Themes/Simples/Home/Index.cshtml
@model IEnumerable<SimpleBlog.ViewModels.PostViewModel>
@{
    ViewBag.Title = "Home Page";
}

@foreach (var post in Model)
{
    <div class="row post">
        <div class="col-lg-12">
            <h2>@post.Title</h2>
            <p class="post-date">
                @post.TimeStamp.ToString("D")
            </p>
            <p class="post-body">
                @Html.Raw(post.BodyHtml)
            </p>
        </div>
    </div>
}

src/SimpleBlog.Web/Views/Themes/Simples/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @{
        var title = await Component.InvokeAsync("SiteTitle");
        var themePath = await Component.InvokeAsync("ThemeContentFolder");
    }
    <title>@ViewBag.Title - @title</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="@themePath/css/site.css" />
</head>
<body>
    <div class="container body-content">
        <h1>@title</h1>
        <hr />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @title</p>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>